Repository iotaledger/wallet.rs, pull requests merged in 2022-04, with the labels that each got.

#969 Match Foundry ID
  src/account/operations/transfer/high_level/mint_native_token.rs
Labels: network:shimmer

#968 Granular output collection
  Cargo.toml
  src/account/mod.rs
  src/account/operations/output_collection.rs
  src/account/operations/syncing/addresses.rs
  src/account/operations/syncing/mod.rs
  src/account/operations/syncing/options.rs
  src/account/operations/transfer/high_level/mint_nfts.rs
  src/message_interface/account_method.rs
  src/message_interface/message_handler.rs
  src/message_interface/response_type.rs
Labels: network:shimmer

#973 Fix message deserialization for old messages
  .changes/message-deserialization.md
  src/message.rs
Labels: network:mainnet, type:fix

#976 Update rust-rocksdb to fix Unicode paths on Windows
  .changes/unicode-paths.md
  Cargo.lock
  Cargo.toml
  bindings/java/Cargo.lock
  bindings/nodejs/Cargo.lock
  bindings/python/native/Cargo.lock
Labels: type:fix

#978 Sync foundry outputs
  .github/workflows/build-and-test.yml
  .github/workflows/clippy.yml
  .github/workflows/coverage.yml
  .github/workflows/format.yml
  .github/workflows/udeps.yml
  Cargo.toml
  bindings/nodejs/Cargo.lock
  bindings/nodejs/Cargo.toml
  bindings/python/native/Cargo.lock
  bindings/python/native/Cargo.toml
  examples/split_funds.rs
  examples/storage.rs
  src/account/operations/syncing/addresses.rs
  src/account/operations/syncing/outputs.rs
  src/events/mod.rs
  src/message_interface/message_type.rs
  src/message_interface/mod.rs
  src/storage/manager.rs
  tests/accounts.rs
Labels: network:shimmer, scope:core

#981 Bump iota.rs commit
  Cargo.toml
  examples/events.rs
  examples/ping.rs
  examples/pong.rs
  examples/split_funds.rs
  examples/threads.rs
  src/account/operations/output_collection.rs
  src/account/operations/output_consolidation.rs
  src/account/operations/transfer/high_level/minimum_storage_deposit.rs
  src/account/operations/transfer/high_level/mint_native_token.rs
  src/account/operations/transfer/high_level/mint_nfts.rs
  src/account/operations/transfer/high_level/send_amount.rs
  src/account/operations/transfer/high_level/send_micro_transaction.rs
  src/account/operations/transfer/high_level/send_native_tokens.rs
  src/account/operations/transfer/high_level/send_nft.rs
  src/error.rs
  src/logger.rs
  src/message_interface/mod.rs
Labels: network:shimmer, scope:dependencies, type:chore

#995 Add dummy test to fix CI
  bindings/python/native/tests/dummy_test.py
Labels: network:shimmer, scope:ci

#986 Update account balance
  bindings/python/native/iota_wallet/account.py
  examples/ping.rs
  examples/pong.rs
  examples/split_funds.rs
  examples/wallet.rs
  src/account/builder.rs
  src/account/handle.rs
  src/account/mod.rs
  src/account/operations/balance.rs
  src/account/operations/balance_finder.rs
  src/account/operations/helpers/time.rs
  src/account/operations/output_collection.rs
  src/account/operations/output_consolidation.rs
  src/account/operations/syncing/addresses.rs
  src/account/operations/syncing/mod.rs
  src/account/operations/syncing/outputs.rs
  src/account/types/address.rs
  src/account/types/mod.rs
  src/account_manager/operations/account_recovery.rs
  src/message_interface/account_method.rs
  src/message_interface/message_handler.rs
  src/message_interface/response_type.rs
Labels: network:shimmer

#997 Ignore errors from posting the message, so transaction doesn't get lost
  src/account/sync/mod.rs
Labels: network:mainnet, scope:core

#998 Update rust-rocksdb to fix illegal instruction on Windows
  .changes/windows-popcnt.md
  Cargo.lock
  Cargo.toml
  bindings/java/Cargo.lock
  bindings/nodejs/Cargo.lock
  bindings/python/native/Cargo.lock
Labels: type:fix

#1003 Add first public address during account discovery if needed
  src/account/sync/mod.rs
Labels: network:mainnet

#985 Fix `cargo doc`
  src/account/operations/mod.rs
  src/account/operations/output_collection.rs
  src/account/operations/syncing/options.rs
  src/account/operations/transfer/high_level/send_nft.rs
Labels: type:chore, scope:docs

#1018 Add get_node_info()
  src/account_manager/mod.rs
  src/message_interface/message_handler.rs
  src/message_interface/message_type.rs
  src/message_interface/response_type.rs
Labels: network:shimmer, scope:core, type:feature

#1016 Add with_coin_type()
  bindings/nodejs/examples/account-manager.js
  src/account/builder.rs
  src/account/types/mod.rs
  src/error.rs
  src/message_interface/message_handler.rs
  src/message_interface/message_type.rs
  src/message_interface/mod.rs
  tests/accounts.rs
Labels: network:shimmer, scope:core, type:enhancement

#1022 Update iota.rs rev to fix nodeinfo
  Cargo.toml
  src/account/operations/helpers/time.rs
  src/account/operations/transfer/high_level/minimum_storage_deposit.rs
  src/account/operations/transfer/high_level/send_micro_transaction.rs
  src/account/operations/transfer/high_level/send_native_tokens.rs
  src/message_interface/mod.rs
Labels: network:shimmer

#1012 Add signature validation
  src/account/sync/mod.rs
  src/error.rs
Labels: network:mainnet
