Repository iotaledger/wallet.rs, pull requests merged in 2022-06, with the labels that each got.

#1115 Add MinimumRequiredStorageDeposit method
  src/message_interface/account_method.rs
  src/message_interface/message_handler.rs
  src/message_interface/response.rs
Labels: network:shimmer

#1121 Expose ChangeStrongholdPassword
  Cargo.toml
  src/account_manager/operations/backup.rs
  src/account_manager/operations/stronghold.rs
  src/message_interface/message.rs
  src/message_interface/message_handler.rs
Labels: network:shimmer

#1130 Don't print DBG logs in examples compiled with --release
  Cargo.toml
Labels: network:shimmer

#1116 Add function to remove the latest account
  src/account_manager/mod.rs
  src/message_interface/account_method.rs
  src/message_interface/message_handler.rs
  tests/accounts.rs
Labels: network:shimmer

#1112 feat: expose output builders
  bindings/nodejs/examples/4b-send-transfer.js
  bindings/nodejs/lib/Account.ts
  bindings/nodejs/types/bridge/account.ts
  bindings/nodejs/types/bridge/index.ts
  bindings/nodejs/types/buildOutputData.ts
Labels: network:shimmer, scope:nodejs, type:feature

#1128 Add native tokens to consolidation
  examples/output_consolidation.rs
  src/account/operations/output_consolidation.rs
  src/account/operations/syncing/mod.rs
  src/message_interface/account_method.rs
  src/message_interface/message_handler.rs
  src/message_interface/response.rs
Labels: network:shimmer

#971 Burn native token and outputs
  examples/11_melt_native_token.rs
  examples/12_burn_native_token.rs
  examples/13_burn_nft.rs
  examples/14_destroy_foundry.rs
  examples/15_destroy_alias.rs
  src/account/operations/address_generation.rs
  src/account/operations/syncing/mod.rs
  src/account/operations/transaction/high_level/burning_melting/burn_native_token.rs
  src/account/operations/transaction/high_level/burning_melting/burn_nft.rs
  src/account/operations/transaction/high_level/burning_melting/destroy_alias.rs
  src/account/operations/transaction/high_level/burning_melting/destroy_foundry.rs
  src/account/operations/transaction/high_level/burning_melting/melt_native_token.rs
  src/account/operations/transaction/high_level/burning_melting/mod.rs
  src/account/operations/transaction/high_level/burning_melting/sweep_outputs.rs
  src/account/operations/transaction/high_level/minting/mint_native_token.rs
  src/account/operations/transaction/high_level/minting/mint_nfts.rs
  src/account/operations/transaction/high_level/minting/mod.rs
  src/account/operations/transaction/high_level/mod.rs
  src/account/operations/transaction/input_selection.rs
  src/account/operations/transaction/options.rs
  src/account/operations/transaction/prepare_transaction.rs
  src/error.rs
  src/lib.rs
  src/message_interface/message_handler.rs
  src/message_interface/response.rs
  tests/burn_outputs.rs
Labels: network:shimmer

#1123 Fix gitignore for Swift bindings
  .gitignore
  bindings/swift/.gitignore
  bindings/swift/Cargo.lock
Labels: network:shimmer, type:chore

#1148 Add db version
  src/storage/constants.rs
  src/storage/manager.rs
Labels: network:shimmer

#1141 Use shimmer coin type as default
  src/account/builder.rs
  tests/accounts.rs
Labels: network:shimmer

#1136 Update workflows to production branch
  .github/workflows/audit.yml
  .github/workflows/build-and-test.yml
  .github/workflows/clippy.yml
  .github/workflows/covector-version-or-publish.yml
  .github/workflows/coverage.yml
  .github/workflows/deploy-docs-to-gh-pages.yml
  .github/workflows/format.yml
  .github/workflows/python_binding_publish.yml
  .github/workflows/udeps.yml
Labels: network:mainnet

#1155 fix: stronghold params optional
  bindings/nodejs/types/secretManager.ts
Labels: scope:nodejs, type:fix

#1152 Use NativeTokens struct in AccountBalance
  bindings/nodejs/tsconfig.json
  bindings/nodejs/types/account.ts
  bindings/nodejs/types/output.ts
  src/account/operations/balance.rs
  src/account/operations/syncing/options.rs
  src/account/types/mod.rs
  src/account_manager/mod.rs
  src/message_interface/dtos.rs
  tests/accounts.rs
  tests/burn_outputs.rs
Labels: network:shimmer

#1156 feat (Python binding): Make API calls up to date
  bindings/python/native/iota_wallet/account.py
  bindings/python/native/iota_wallet/wallet.py
Labels: network:shimmer, scope:python

#1157 Expose address conversion methods
  bindings/nodejs/examples/20-address-conversion.js
  bindings/nodejs/lib/Account.ts
  bindings/nodejs/lib/AccountManager.ts
  bindings/nodejs/types/bridge/account.ts
  bindings/nodejs/types/bridge/accountManager.ts
  bindings/nodejs/types/bridge/index.ts
  src/message_interface/message.rs
  src/message_interface/message_handler.rs
  src/message_interface/mod.rs
  src/message_interface/response.rs
Labels: network:shimmer, scope:nodejs, scope:message_interface

#1158 Build output builders from existing outputs
  src/account/operations/transaction/high_level/burning_melting/burn_native_token.rs
  src/account/operations/transaction/high_level/minting/mint_native_token.rs
  src/account/operations/transaction/high_level/send_nft.rs
Labels: network:shimmer

#1173 Delete accounts and db together
  bindings/nodejs/examples/5-backup.js
  bindings/nodejs/lib/AccountManager.ts
  bindings/nodejs/types/bridge/accountManager.ts
  bindings/nodejs/types/bridge/index.ts
  bindings/python/native/iota_wallet/wallet.py
  src/account_manager/mod.rs
  src/message_interface/message.rs
  src/message_interface/message_handler.rs
  src/message_interface/response.rs
Labels: network:shimmer

#1171 Fix restore_backup
  src/account_manager/operations/backup.rs
  tests/backup_restore.rs
Labels: network:shimmer

#1175 fix: collect outputs parameters
  Cargo.toml
  bindings/nodejs/Cargo.lock
  bindings/nodejs/examples/21-collect-outputs.js
  bindings/nodejs/examples/8-logger.js
  bindings/nodejs/lib/Account.ts
  bindings/nodejs/types/outputOptions.ts
  src/message_interface/account_method.rs
Labels: scope:nodejs, type:fix

#1193 Fix balance, use provided time
  src/account/operations/balance.rs
  src/account/operations/helpers/time.rs
  src/account/operations/transaction/high_level/send_micro_transaction.rs
  src/account/operations/transaction/high_level/send_native_tokens.rs
Labels: network:shimmer

#1168 Make account recovery fast
  src/account/operations/balance_finder.rs
  src/account_manager/operations/account_recovery.rs
Labels: network:shimmer

#1199 Request outputs with expiration and storage deposit return unlock condition
  src/account/operations/syncing/addresses.rs
Labels: network:shimmer

#1203 Parallel output syncing
  src/account/operations/syncing/addresses.rs
Labels: network:shimmer

#1205 chore: update types
  bindings/nodejs/types/outputOptions.ts
  src/events/types.rs
Labels: type:chore

#1187 Bump neon version
  .github/workflows/format.yml
  bindings/nodejs/Cargo.lock
  bindings/nodejs/Cargo.toml
  bindings/nodejs/src/classes/account/mod.rs
  bindings/nodejs/src/classes/account_manager/mod.rs
  rustfmt.toml
Labels: network:mainnet, scope:nodejs

#1210 Rename collect outputs to claim outputs
  bindings/nodejs/examples/13-get-outputs-with-additional-unlock-conditions.js
  bindings/nodejs/examples/21-claim-outputs.js
  bindings/nodejs/lib/Account.ts
  bindings/nodejs/types/bridge/account.ts
  bindings/nodejs/types/bridge/index.ts
  bindings/nodejs/types/output.ts
  bindings/python/native/iota_wallet/account.py
  src/account/mod.rs
  src/account/operations/balance.rs
  src/account/operations/mod.rs
  src/account/operations/output_claiming.rs
  src/message_interface/account_method.rs
  src/message_interface/message_handler.rs
  src/message_interface/mod.rs
  src/message_interface/response.rs
  tests/burn_outputs.rs
Labels: network:shimmer

#1215 Update covector-version-or-publish.yml
  .github/workflows/covector-version-or-publish.yml
Labels: scope:ci

#1204 Filter inputs in input selection
  src/account/operations/balance.rs
  src/account/operations/transaction/input_selection.rs
Labels: network:shimmer

#1213 Fix restore_accounts
  src/account/operations/mod.rs
  src/account/operations/output_finder.rs
  src/account_manager/operations/account_recovery.rs
Labels: network:shimmer

#1218 fix: add features upon release
  .changes/add-features.md
  .changes/config.json
Labels: scope:ci, scope:nodejs

#1225 Update covector workflow to use windows-2019 and only newer node.js v…
  .github/workflows/covector-version-or-publish.yml
Labels: scope:ci, scope:nodejs

#1228 chore: prerelease on npm
  .changes/add-types.md
  .changes/pre-release.md
  .changes/pre.json
  bindings/nodejs/package.json
Labels: scope:nodejs, type:chore

#1236 fix: update covector commands
  .changes/config.json
  .changes/pre-release.md
Labels: scope:nodejs
