Repository iotaledger/wallet.rs, pull requests merged in 2022-05, with the labels that each got.

#1024 Update iota.rs rev
  Cargo.toml
Labels: network:shimmer, type:fix

#1029 Fix nodejs ci by keeping package.json
  bindings/nodejs/.gitignore
  bindings/nodejs/lib/package.json
Labels: network:mainnet, scope:ci, scope:nodejs

#1032 Update iota.rs rev to fix input selection
  Cargo.toml
Labels: network:shimmer, type:fix

#1034 Fix account creation with Stronghold
  src/account/builder.rs
  tests/accounts.rs
Labels: network:shimmer, type:fix

#1036 Use Id::null instead of from(array)
  Cargo.toml
  src/account/operations/transfer/high_level/minimum_storage_deposit.rs
  src/account/operations/transfer/high_level/mint_native_token.rs
  src/account/operations/transfer/high_level/mint_nfts.rs
Labels: priority:4, scope:core, type:chore

#1042 Use AliasAddress QueryParameter for foundry outputs
  Cargo.toml
  src/account/operations/syncing/addresses.rs
Labels: network:shimmer, type:fix

#1047 Expose recover_accounts in message_interface
  Cargo.toml
  src/account/operations/transfer/prepare_transaction.rs
  src/account_manager/operations/account_recovery.rs
  src/message_interface/message_handler.rs
  src/message_interface/message_type.rs
Labels: network:shimmer, scope:message_interface

#1044 Add custom de/serialization for CoinType
  src/account/builder.rs
  src/account/types/mod.rs
Labels: network:shimmer

#1050 fix: move get node info
  bindings/nodejs/examples/10-node-info.js
  bindings/nodejs/lib/Account.ts
  bindings/nodejs/lib/AccountManager.ts
  bindings/nodejs/types/bridge/account.ts
  bindings/nodejs/types/bridge/accountManager.ts
  bindings/nodejs/types/bridge/index.ts
Labels: scope:nodejs, type:fix

#1007 Remove minimum storage deposit functions
  src/account/operations/transfer/high_level/minimum_storage_deposit.rs
  src/account/operations/transfer/high_level/mint_native_token.rs
  src/account/operations/transfer/high_level/mint_nfts.rs
Labels: network:shimmer, priority:1, scope:core, type:enhancement

#1048 Add get_output
  src/account/handle.rs
  src/message_interface/account_method.rs
  src/message_interface/message_handler.rs
  src/message_interface/response_type.rs
Labels: network:shimmer

#1051 feat: coin type optional
  bindings/nodejs/examples/1-create-account.js
  bindings/nodejs/lib/AccountManager.ts
  bindings/nodejs/types/account.ts
Labels: network:shimmer

#1019 Backup
  Cargo.toml
  bindings/nodejs/Cargo.lock
  bindings/nodejs/Cargo.toml
  bindings/nodejs/lib/AccountManager.ts
  bindings/nodejs/src/message_handler.rs
  bindings/nodejs/types/bridge/accountManager.ts
  bindings/python/native/Cargo.lock
  examples/02_generate_address.rs
  examples/03_get_funds.rs
  examples/04_get_balance.rs
  examples/05_transaction.rs
  examples/06_send_micro_transaction.rs
  examples/07_send_native_tokens.rs
  examples/08_send_nft.rs
  examples/09_mint_native_token.rs
  examples/10_mint_nft.rs
  src/account/builder.rs
  src/account/mod.rs
  src/account/operations/address_generation.rs
  src/account/types/address.rs
  src/account_manager/builder.rs
  src/account_manager/mod.rs
  src/account_manager/operations/backup.rs
  src/account_manager/operations/mod.rs
  src/error.rs
  src/message_interface/account_method.rs
  src/message_interface/message.rs
  src/message_interface/message_handler.rs
  src/message_interface/message_type.rs
  src/message_interface/mod.rs
  src/message_interface/response.rs
  src/message_interface/response_type.rs
  src/storage/constants.rs
  src/storage/manager.rs
  tests/account_recovery.rs
  tests/accounts.rs
  tests/backup_restore.rs
Labels: network:shimmer, type:feature

#1058 Add debug logs to message_interface without leaking secrets
  bindings/nodejs/src/message_handler.rs
  src/message_interface/message_handler.rs
  src/message_interface/message_type.rs
  src/message_interface/response.rs
Labels: network:shimmer, scope:message_interface

#1021 Add dtos for exposed structs with amount
  src/account/mod.rs
  src/account/operations/transfer/high_level/mint_nfts.rs
  src/account/operations/transfer/high_level/send_amount.rs
  src/account/operations/transfer/high_level/send_micro_transaction.rs
  src/account/operations/transfer/high_level/send_nft.rs
  src/account/types/address.rs
  src/account/types/mod.rs
  src/message_interface/account_method.rs
  src/message_interface/dtos.rs
  src/message_interface/message_handler.rs
  src/message_interface/message_type.rs
  src/message_interface/mod.rs
  src/message_interface/response.rs
Labels: network:shimmer

#1061 Update GetNodeInfo to also accept a provided url
  bindings/nodejs/lib/AccountManager.ts
  bindings/nodejs/types/bridge/accountManager.ts
  src/message_interface/message_handler.rs
  src/message_interface/message_type.rs
Labels: network:shimmer

#927 docs: add a branch section in README
  README.md
Labels: scope:project, type:documentation

#1063 Update transaction creation
  Cargo.toml
  bindings/java/native/Cargo.toml
  bindings/java/native/src/classes/account_manager/acc_manager.rs
  bindings/java/native/src/classes/event_listener/event_manager.rs
  bindings/nodejs/Cargo.lock
  bindings/nodejs/Cargo.toml
  bindings/nodejs/src/lib.rs
  bindings/python/native/Cargo.lock
  bindings/python/native/Cargo.toml
  bindings/python/native/src/lib.rs
  bindings/swift/Cargo.toml
  docs/overview.md
  src/account/builder.rs
  src/account/constants.rs
  src/account/operations/address_generation.rs
  src/account/operations/balance_finder.rs
  src/account/operations/syncing/mod.rs
  src/account/operations/transfer/build_transaction.rs
  src/account/operations/transfer/mod.rs
  src/account/operations/transfer/prepare_transaction.rs
  src/account/operations/transfer/sign_transaction.rs
  src/account/types/address.rs
  src/events/mod.rs
  src/events/types.rs
Labels: network:shimmer, type:refactor

#1064 Add destroy method to nodejs binding
  bindings/nodejs/lib/AccountManager.ts
  bindings/nodejs/lib/MessageHandler.ts
  bindings/nodejs/lib/bindings.ts
  bindings/nodejs/src/lib.rs
  bindings/nodejs/src/message_handler.rs
Labels: network:shimmer, scope:nodejs

#1020 Configure ESLint and Prettier
  bindings/nodejs/.eslintignore
  bindings/nodejs/.eslintrc.js
  bindings/nodejs/.prettierrc.js
  bindings/nodejs/.prettierrc.json
  bindings/nodejs/lib/Account.ts
  bindings/nodejs/lib/AccountManager.ts
  bindings/nodejs/lib/MessageHandler.ts
  bindings/nodejs/lib/bindings.ts
  bindings/nodejs/lib/index.ts
  bindings/nodejs/package-lock.json
  bindings/nodejs/package.json
  bindings/nodejs/tsconfig.json
  bindings/nodejs/types/account.ts
  bindings/nodejs/types/accountManager.ts
  bindings/nodejs/types/address.ts
  bindings/nodejs/types/bridge/account.ts
  bindings/nodejs/types/bridge/accountManager.ts
  bindings/nodejs/types/bridge/index.ts
  bindings/nodejs/types/event.ts
  bindings/nodejs/types/index.ts
  bindings/nodejs/types/loggerConfig.ts
  bindings/nodejs/types/network.ts
  bindings/nodejs/types/output.ts
  bindings/nodejs/types/secretManager.ts
  bindings/nodejs/types/transaction.ts
  bindings/nodejs/types/transfer.ts
Labels: network:shimmer, scope:nodejs, javascript

#1068 Refactor balance check for alias and foundry output
  src/account/operations/balance.rs
Labels: network:shimmer

#1071 Add clear_stronghold_password() and is_stronghold_password_available()
  Cargo.toml
  src/account/operations/helpers/time.rs
  src/account_manager/mod.rs
  src/account_manager/operations/mod.rs
  src/account_manager/operations/stronghold.rs
  src/message_interface/message_handler.rs
  src/message_interface/message_type.rs
  src/message_interface/response.rs
Labels: network:shimmer, type:feature

#1073 Expose SetAlias in message_interface
  src/message_interface/account_method.rs
  src/message_interface/message_handler.rs
Labels: network:shimmer

#1081 Remove MessageType
  bindings/nodejs/src/message_handler.rs
  bindings/python/native/src/lib.rs
  bindings/swift/src/lib.rs
  src/message_interface/message.rs
  src/message_interface/message_handler.rs
  src/message_interface/message_type.rs
  src/message_interface/mod.rs
  src/message_interface/response.rs
Labels: network:shimmer

#1079 Expose SetStrongholdPasswordClearInterval
  Cargo.toml
  examples/01_create_wallet.rs
  src/account/types/mod.rs
  src/account_manager/operations/backup.rs
  src/account_manager/operations/stronghold.rs
  src/message_interface/message.rs
  src/message_interface/message_handler.rs
  src/message_interface/response.rs
  tests/accounts.rs
  tests/backup_restore.rs
Labels: network:shimmer, type:feature

#1067 Offline signing
  .gitignore
  Cargo.toml
  examples/offline_signing/0_generate_addresses.rs
  examples/offline_signing/1_prepare_transaction.rs
  examples/offline_signing/2_sign_transaction.rs
  examples/offline_signing/3_send_transaction.rs
  src/account/builder.rs
  src/account/mod.rs
  src/account/operations/balance.rs
  src/account/operations/helpers/time.rs
  src/account/operations/output_collection.rs
  src/account/operations/output_consolidation.rs
  src/account/operations/transfer/high_level/mint_nfts.rs
  src/account/operations/transfer/high_level/send_amount.rs
  src/account/operations/transfer/high_level/send_micro_transaction.rs
  src/account/operations/transfer/high_level/send_native_tokens.rs
  src/account/operations/transfer/high_level/send_nft.rs
  src/account/operations/transfer/mod.rs
  src/account/operations/transfer/prepare_transaction.rs
  src/account/operations/transfer/sign_transaction.rs
  src/account/types/address.rs
  src/account/types/mod.rs
  src/account_manager/builder.rs
  src/events/mod.rs
  src/events/types.rs
  src/lib.rs
  src/message_interface/account_method.rs
  src/message_interface/dtos.rs
  src/message_interface/message_handler.rs
  src/message_interface/mod.rs
  src/message_interface/response.rs
Labels: network:shimmer, type:feature

#1088 fix: remainder strategy
  bindings/nodejs/types/transfer.ts
  src/account/operations/transfer/options.rs
Labels: scope:nodejs, type:fix

#1086 Update and emit events
  Cargo.toml
  src/account/operations/address_generation.rs
  src/account/operations/syncing/mod.rs
  src/account/operations/transfer/build_transaction.rs
  src/events/mod.rs
  src/events/types.rs
  src/message_interface/dtos.rs
  src/message_interface/mod.rs
Labels: network:shimmer

#1091 feat: get transaction
  bindings/nodejs/examples/15-get-transaction.js
  bindings/nodejs/lib/Account.ts
  bindings/nodejs/types/account.ts
  bindings/nodejs/types/address.ts
  bindings/nodejs/types/bridge/account.ts
  bindings/nodejs/types/bridge/index.ts
  bindings/nodejs/types/output.ts
  bindings/nodejs/types/transaction.ts
  src/account/handle.rs
  src/message_interface/account_method.rs
  src/message_interface/message_handler.rs
  src/message_interface/response.rs
Labels: scope:nodejs, type:feature

#1092 Use OutputMetadataResponse instead of OutputResponse
  src/account/operations/syncing/mod.rs
  src/account/operations/syncing/outputs.rs
  src/account/types/mod.rs
  src/message_interface/dtos.rs
Labels: network:shimmer

#1072 Add cargo profiles
  Cargo.toml
Labels: network:shimmer, type:chore

#1094 fix: correct return types
  bindings/java/examples/basic-app/src/main/java/org/example/ExampleApp.java
  bindings/java/native/src/classes/account/acc.rs
  bindings/java/native/src/classes/account_manager/acc_manager.rs
  bindings/java/native/src/classes/event_listener/event_manager.rs
  bindings/java/native/src/classes/message.rs
  bindings/java/native/src/java_glue.rs.in
  bindings/nodejs/examples/4b-send-transfer.js
  bindings/nodejs/examples/7-events.js
  bindings/nodejs/lib/Account.ts
  bindings/nodejs/types/bridge/account.ts
  bindings/nodejs/types/bridge/index.ts
  bindings/nodejs/types/event.ts
  bindings/nodejs/types/index.ts
  bindings/nodejs/types/transaction.ts
  bindings/nodejs/types/transactionOptions.ts
  bindings/python/README.md
  bindings/python/native/iota_wallet/account.py
  bindings/swift/xcode/IotaWallet/IotaWalletTests/await.swift
  docs/overview.md
  documentation/docs/libraries/nodejs/api_reference.md
  documentation/docs/libraries/python/api_reference.md
  documentation/docs/libraries/python/examples.mdx
  documentation/docs/libraries/rust/examples.mdx
  documentation/docs/specification.md
  examples/05_transaction.rs
  examples/06_send_micro_transaction.rs
  examples/07_send_native_tokens.rs
  examples/08_send_nft.rs
  examples/09_mint_native_token.rs
  examples/10_mint_nft.rs
  src/account/mod.rs
  src/account/operations/address_generation.rs
  src/account/operations/mod.rs
  src/account/operations/output_collection.rs
  src/account/operations/output_consolidation.rs
  src/account/operations/transaction/build_transaction.rs
  src/account/operations/transaction/high_level/minimum_storage_deposit.rs
  src/account/operations/transaction/high_level/mint_native_token.rs
  src/account/operations/transaction/high_level/mint_nfts.rs
  src/account/operations/transaction/high_level/mod.rs
  src/account/operations/transaction/high_level/send_amount.rs
  src/account/operations/transaction/high_level/send_micro_transaction.rs
  src/account/operations/transaction/high_level/send_native_tokens.rs
  src/account/operations/transaction/high_level/send_nft.rs
  src/account/operations/transaction/input_selection.rs
  src/account/operations/transaction/mod.rs
  src/account/operations/transaction/options.rs
  src/account/operations/transaction/prepare_transaction.rs
  src/account/operations/transaction/sign_transaction.rs
  src/account/operations/transaction/submit_transaction.rs
  src/error.rs
  src/events/mod.rs
  src/events/types.rs
  src/lib.rs
  src/message_interface/account_method.rs
  src/message_interface/message_handler.rs
  src/message_interface/mod.rs
  src/message_interface/response.rs
Labels: scope:nodejs, type:chore

#1100 feat: expose offline signing methods
  bindings/nodejs/examples/16a-prepare-and-send-amount.js
  bindings/nodejs/examples/2-generate-address.js
  bindings/nodejs/lib/Account.ts
  bindings/nodejs/types/bridge/account.ts
  bindings/nodejs/types/bridge/index.ts
  bindings/nodejs/types/output.ts
  bindings/nodejs/types/remainderData.ts
  bindings/nodejs/types/signedTransactionEssence.ts
  bindings/nodejs/types/transaction.ts
Labels: network:shimmer, scope:nodejs

#1105 Return better error
  src/account/operations/output_collection.rs
Labels: network:shimmer

#1107 Unlock inputs from conflicting transactions
  src/account/operations/transaction/mod.rs
Labels: network:shimmer

#1106 Clean syncing
  src/account/builder.rs
  src/account/mod.rs
  src/account/operations/output_consolidation.rs
  src/account/operations/syncing/addresses.rs
  src/account/operations/syncing/mod.rs
  src/account/operations/syncing/options.rs
  src/account/operations/transaction/mod.rs
  src/message_interface/dtos.rs
Labels: network:shimmer

#1098 Add output builder to message_interface
  Cargo.toml
  src/message_interface/account_method.rs
  src/message_interface/message_handler.rs
  src/message_interface/response.rs
Labels: network:shimmer

#1099 Remove Chrysalis docs
  documentation/docs/libraries/nodejs/api_reference.md
  documentation/docs/libraries/nodejs/examples.mdx
  documentation/docs/libraries/overview.md
  documentation/docs/libraries/python/api_reference.md
  documentation/docs/libraries/python/examples.mdx
  documentation/docs/libraries/python/getting_started.md
  documentation/docs/libraries/rust/examples.mdx
  documentation/docs/libraries/rust/getting_started.md
  documentation/docs/overview.md
  documentation/docs/specification.md
  documentation/docs/welcome.md
  documentation/sidebars.js
Labels: network:shimmer, scope:docs

#1109 Participation changes for voting
  src/account/mod.rs
  src/account/sync/mod.rs
  src/account_manager.rs
  src/participation/account_helpers.rs
  src/participation/response_types.rs
  src/participation/types.rs
  src/storage/mod.rs
Labels: network:mainnet
