Repository iotaledger/wallet.rs, pull requests merged in 2022-02, with the labels that each got.

#881 Add manager options when creating message handler
  src/message_interface/mod.rs
Labels: N - shimmer

#887 Update to latest iota.rs rev and cleanup errors
  Cargo.toml
  src/account/builder.rs
  src/account/operations/transfer/prepare_transaction.rs
  src/account/operations/transfer/sign_transaction.rs
  src/error.rs
  src/lib.rs
Labels: N - shimmer

#890 Remove attack-a-thon submission template
  .github/ISSUE_TEMPLATE/attack_a_thon.md
Labels: scope:misc

#891 Add code of conduct
  CODE_OF_CONDUCT.md
Labels: scope:misc

#892 Add bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: scope:misc

#893 Add a task creation template
  .github/ISSUE_TEMPLATE/create-task.yml
Labels: scope:misc

#894 Cleanup and fix some syncing issues
  .gitignore
  README.md
  documentation/docs/libraries/rust/getting_started.md
  examples/accounts.rs
  examples/address_generation.rs
  examples/background_syncing.rs
  examples/events.rs
  examples/ping.rs
  examples/pong.rs
  examples/recover_accounts.rs
  examples/split_funds.rs
  examples/storage.rs
  examples/threads.rs
  examples/wallet.rs
  src/account/builder.rs
  src/account/constants.rs
  src/account/handle.rs
  src/account/mod.rs
  src/account/operations/address_generation.rs
  src/account/operations/balance_finder.rs
  src/account/operations/output_consolidation.rs
  src/account/operations/syncing/addresses.rs
  src/account/operations/syncing/mod.rs
  src/account/operations/syncing/outputs.rs
  src/account/operations/syncing/transactions.rs
  src/account/operations/transfer/input_selection.rs
  src/account/operations/transfer/mod.rs
  src/account/operations/transfer/prepare_transaction.rs
  src/account/operations/transfer/submit_transaction.rs
  src/account/types/address.rs
  src/account/types/mod.rs
  src/account_manager/builder.rs
  src/account_manager/mod.rs
  src/account_manager/operations/get_account.rs
  src/client.rs
  src/lib.rs
  src/message_interface/message_type.rs
  src/message_interface/mod.rs
  tests/account_recovery.rs
Labels: network:shimmer, type:enhancement

#897 Message interface events
  src/message_interface/message_handler.rs
  src/message_interface/mod.rs
Labels: network:shimmer

#898 Add event listener to nodejs binding
  bindings/nodejs/Cargo.lock
  bindings/nodejs/Cargo.toml
  bindings/nodejs/examples/2-generate-address.js
  bindings/nodejs/examples/7-events.js
  bindings/nodejs/examples/8-logger.js
  bindings/nodejs/lib/eventListener.js
  bindings/nodejs/lib/index.js
  bindings/nodejs/lib/messages/account.js
  bindings/nodejs/lib/messages/accountManager.js
  bindings/nodejs/lib/messages/messageHandler.js
  bindings/nodejs/src/event_listener.rs
  bindings/nodejs/src/lib.rs
  bindings/nodejs/src/message_handler.rs
  bindings/nodejs/src/types.rs
  src/account/types/mod.rs
  src/events/types.rs
  src/message_interface/mod.rs
Labels: network:shimmer, scope:nodejs, type:feature
