Repository iotaledger/wallet.rs, pull requests merged in 2022-11, with the labels that each got.

#1534 chore: improve output metadata request
  CHANGELOG.md
  src/account/operations/syncing/mod.rs
  src/account/update.rs
Labels: task

#1555 fix: explicit installation of typescript as a dependency
  .github/workflows/covector-version-or-publish.yml
Labels: bug

#1556 feat: update account methods
  .changes/get-incoming-tx.md
  .changes/incomingtransactionstype.md
  .changes/pre.json
  bindings/nodejs/lib/Account.ts
  bindings/nodejs/types/bridge/account.ts
  bindings/nodejs/types/bridge/index.ts
  bindings/nodejs/types/incomingTransactionData.ts
  bindings/nodejs/types/index.ts
Labels: version updates

#1551 chore: improve output consolidation logic
  .changes/improve-consolidation-logic.md
  examples/output_consolidation.rs
  src/account/operations/output_consolidation.rs
Labels: task

#1564 fix: set minimum macOS version to 10.12
  .github/workflows/covector-version-or-publish.yml
Labels: bug

#1565 fix: statically link c runtime when building windows binaries
  bindings/nodejs/.cargo/config.toml
Labels: bug

#1567 chore: add sender and issuer to features
  bindings/nodejs/types/outputOptions.ts
Labels: task
