Repository iotaledger/wallet.rs, pull requests merged in 2022-07, with the labels that each got.

#1248 fix: add yarn before tsc
  .changes/config.json
  .changes/typescript-fix-declarations.md
Labels: scope:nodejs

#1232 Add option to sync incoming transactions
  src/account/builder.rs
  src/account/handle.rs
  src/account/mod.rs
  src/account/operations/syncing/addresses.rs
  src/account/operations/syncing/mod.rs
  src/account/operations/syncing/options.rs
  src/account/operations/syncing/outputs.rs
  src/message_interface/account_method.rs
  src/message_interface/message_handler.rs
  src/message_interface/response.rs
Labels: network:shimmer

#1254 Fix account recovery
  src/account_manager/operations/account_recovery.rs
Labels: network:shimmer

#1253 Node.js Ledger Nano support
  .changes/config.json
  Cargo.toml
  bindings/nodejs/Cargo.lock
  bindings/nodejs/Cargo.toml
  bindings/nodejs/lib/AccountManager.ts
  bindings/nodejs/types/bridge/accountManager.ts
  bindings/nodejs/types/bridge/index.ts
  bindings/nodejs/types/secretManager.ts
  examples/ledger_nano.rs
  src/account/operations/address_generation.rs
  src/account/operations/output_consolidation.rs
  src/account/operations/transaction/sign_transaction.rs
  src/account_manager/operations/ledger_nano.rs
Labels: network:shimmer, scope:nodejs

#1262 chore: update `wallet.rs` version
  .changes/initial-ledger-support.md
Labels: scope:nodejs, type:chore

#1256 Get foundry output by native token ID
  bindings/nodejs/examples/22-mint-native-tokens.js
  bindings/nodejs/examples/23-get-foundry-output.js
  bindings/nodejs/lib/Account.ts
  bindings/nodejs/lib/AccountManager.ts
  bindings/nodejs/lib/MessageHandler.ts
  bindings/nodejs/types/bridge/account.ts
  bindings/nodejs/types/bridge/index.ts
  bindings/nodejs/types/index.ts
  bindings/nodejs/types/outputOptions.ts
  bindings/nodejs/types/transactionOptions.ts
  src/account/handle.rs
  src/message_interface/account_method.rs
  src/message_interface/message_handler.rs
  src/message_interface/response.rs
Labels: network:shimmer

#1279 Remove amout field from OutputData and duplicated OutputDataDto
  bindings/nodejs/types/output.ts
  examples/output_consolidation.rs
  src/account/operations/balance.rs
  src/account/operations/output_consolidation.rs
  src/account/operations/syncing/outputs.rs
  src/account/operations/transaction/high_level/burning_melting/destroy_foundry.rs
  src/account/operations/transaction/high_level/burning_melting/sweep_outputs.rs
  src/account/types/mod.rs
  src/account/update.rs
  src/message_interface/dtos.rs
  src/message_interface/message_handler.rs
  src/message_interface/response.rs
Labels: network:shimmer

#1278 Fix set_client_options to include coin type
  src/account/update.rs
  src/account_manager/builder.rs
  src/account_manager/mod.rs
Labels: network:shimmer

#1291 Update to latest iota.rs rev
  Cargo.toml
  src/account/operations/syncing/addresses.rs
  src/account/operations/transaction/input_selection.rs
  src/account/update.rs
Labels: network:shimmer

#1298 Update property name for tokenId
  .changes/stardust-release.md
  bindings/nodejs/types/account.ts
Labels: javascript

#1297 Increase consolidation inputs
  src/account/constants.rs
  src/account/operations/output_consolidation.rs
Labels: network:shimmer

#1307 Include @iota/types in dependencies
  .changes/types.md
  .github/workflows/covector-version-or-publish.yml
  bindings/nodejs/Cargo.lock
  bindings/nodejs/package.json
  bindings/nodejs/yarn.lock
Labels: network:shimmer, scope:nodejs
