Repository iotaledger/wallet.rs, pull requests merged in 2023-01, with the labels that each got.

#1717 chore: update NodeJS bindings for participation method
  Cargo.toml
  bindings/nodejs/lib/AccountManager.ts
  bindings/nodejs/types/bridge/accountManager.ts
  bindings/nodejs/types/bridge/index.ts
  src/message_interface/message.rs
  src/message_interface/message_handler.rs
  src/message_interface/response.rs
Labels: task

#1727 chore: add more alignment for participation code
  .changes/participation-rename.md
  Cargo.toml
  bindings/nodejs/Cargo.lock
  bindings/nodejs/examples/29-voting.js
  bindings/nodejs/lib/Account.ts
  bindings/nodejs/lib/AccountManager.ts
  bindings/nodejs/types/bridge/account.ts
  bindings/nodejs/types/bridge/accountManager.ts
  bindings/nodejs/types/bridge/index.ts
  bindings/nodejs/types/participation.ts
  examples/participation.rs
  src/account/operations/participation/mod.rs
  src/account/operations/participation/voting.rs
  src/account_manager/operations/participation.rs
  src/message_interface/account_method.rs
  src/message_interface/message.rs
  src/message_interface/response.rs
  src/storage/participation.rs
Labels: task

#1752 fix: tag-prefix passed as a string
  bindings/nodejs/package.json
Labels: bug

#1757 fix: manually download windows arm64 build
  .github/workflows/covector-version-or-publish.yml
  bindings/nodejs/scripts/download-node-lib-win-arm64.ps1
Labels: bug, dependencies
